# Project information
site_name: Technical-Write Me - API Documentation Samples
# site_url:
site_author: Javier Hern치ndez Fern치ndez
site_description: >-
  My API documentation showcase as Senior Technical Writer and Documentation Manager.

# Repository
# repo_name: 
repo_url: https://github.com/javierhf/technical-write-me
#edit_uri: 
# Copyright
copyright: Copyright &copy; 2024 Javier Hern치ndez Fern치ndez

# Configuration
theme:
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.indexes
    #- toc.integrate
    - toc.follow
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
  palette:
    - scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode    
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  icon:
    logo: assets/cube.png
  logo: assets/cube.png

  extra:
  status:
    new: Recently added
    deprecated: Outdated article


# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - tables
  - fenced_code
  - meta
  - wikilinks
  - md_in_html
  - sane_lists
  - toc:
      # permalink: true
      permalink: '#'
      baselevel: 1
      separator: '_'
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Plugins  
# Page tree
nav:
  - Home: index.md  
  - Open Weather API:   
      - Conceptual Documentation:  
          - Overview: openweather/index.md    
          - Getting Started: openweather/getting-started/index.md  
          - Authentication and Authorization: openweather/authentication-authorization/index.md  
          - Best Practices: openweather/best-practices/index.md  
          - Glossary: openweather/glossary/index.md  
      - API Reference: openweather/reference/index.md  

  - Swagger Pet Store:   
      - Getting Started: swagger-pet-store/index.md    
      - Tutorials: 
         - Showing All Pets in my Store: swagger-pet-store/tutorials/show-all-pets/index.md   
         - Finding Pets by Status: swagger-pet-store/tutorials/finding-pets-bystatus/index.md   
         - Finding a Pet by ID: swagger-pet-store/tutorials/finding-pet-byid/index.md   
         - Finding an Order by ID: swagger-pet-store/tutorials/finding-order-byid/index.md   
      - API Reference: swagger-pet-store/index.md 